# -*- coding: utf-8 -*-
"""JuntarDados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wpMGxnfcV-5vXu9OiHsIWyiukKaP4NHb
"""

import pandas as pd

ativos = pd.read_excel('./exemplo_dados.xlsx',sheet_name='ativos')
ativos

contas = pd.read_excel('./exemplo_dados.xlsx',sheet_name='contas')
contas

aplicacoes = pd.read_excel('./exemplo_dados.xlsx',sheet_name='aplicacoes')
aplicacoes

resultado = aplicacoes.merge(ativos,'left',left_on=['ATIVO'],right_on=['ID_ATIVO'])

resultado.to_csv('./resultado_pyton.csv',sep=';',decimal=',',index=False)

